name: CI

on:
  push:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 
      uses: actions/setup-python@v4      
      with:
        python-version: "3.12.3"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests geojson pandas pytest
        
    - name: Run tests
      run: |
        chmod +x ./project/tests.sh
        ./project/tests.sh
