
name: CI

on:
  push:
    branches: 
      - main
  


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 
      uses: actions/setup-python@v3      
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas sqlite3
        
    - name: Run tests
      run: |
        chmod +x test.sh
        ../project/tests.sh
